#!/bin/bash

#rm -rf ./build/* &> /dev/null
rm -rf ./build-debug/* &> /dev/null
rm -rf ./build-release/* &> /dev/null
#rm -r ./extern/googletest/lib/* &> /dev/null
rm -r ./lib/* &> /dev/null
rm -r ./test/bin/* &> /dev/null
rm -r ./benchmark/bin/* &> /dev/null
#rm ./CMakeCache.txt &> /dev/null
#rm ./cmake_install.cmake &> /dev/null
#rm ./Makefile &> /dev/null


