#!/bin/bash



./build_all

# Check if cmd failed, if res != 0
if [[ $? -ne 0 ]]; then
    exit 1 
fi 



echo " "
echo " "



# ./test/bin/test_insight
./examples/bin/example_mnist

# Check if cmd failed, if res != 0
if [[ $? -ne 0 ]]; then
    exit 1 
fi 
