name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test.${{ matrix.c++-compiler }}.${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Release']
        c-compiler: [gcc-10, clang]
        c++-compiler: [g++-10, clang]

    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
          
      - name: test1
        shell: bash
        run: cmake -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.c++-compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -B ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.c-compiler }}
          CXX: ${{ matrix.c++-compiler }}
        
      - name: test2
        shell: bash
        run: cmake --build ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.c-compiler }}
          CXX: ${{ matrix.c++-compiler }}
