name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
          
      - name: test1
        continue-on-error: true
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release -B ./build-release
        env:
          CC:  gcc-10
          CXX: g++-10
        
      - name: test2
        continue-on-error: true
        shell: bash
        run: cmake --build ./build-release
        env:
          CC:  gcc-10
          CXX: g++-10
