name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test.${{ matrix.os }}.${{ matrix.config.cxx }}.${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        build_type: ['Release', 'Debug']
        config:
        - {c: gcc-10, cxx: g++-10}
        #- {c: clang, cxx: clang++}
        
    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
      
      
      - name: install_gcc_macos
        if: matrix.os == 'macos-10.15'
        run: brew install gcc@10
          
          
      - name: configure
        run: cmake -DCMAKE_C_COMPILER=${{ matrix.config.c }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
                   -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -B ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.config.c }}
          CXX: ${{ matrix.config.cxx }}
        
        
      - name: build
        run: cmake --build ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.config.c }}
          CXX: ${{ matrix.config.cxx }}
          
      
      - name: test
        working-directory: ${{ github.workspace }}/build-${{ matrix.build_type }}
        run: ctest --output-on-failure


