name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
          
      - name: test4
        shell: bash
        run: |
          cmake -DCMAKE_CXX_COMPILER=gcc-10 -DCMAKE_BUILD_TYPE=Release -B ./build-release
          cat /home/runner/work/insight/insight/build-release/CMakeFiles/CMakeOutput.log
          cat /home/runner/work/insight/insight/build-release/CMakeFiles/CMakeError.log
      
      

