name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test.${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']

    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
          
      - name: test1
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -B ./build-${{ matrix.build_type }}
        env:
          CC:  gcc-10
          CXX: g++-10
        
      - name: test2
        shell: bash
        run: cmake --build ./build-${{ matrix.build_type }}
        env:
          CC:  gcc-10
          CXX: g++-10
