name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2

      - name: test1
        shell: bash
        run: echo $GITHUB_WORKSPACE
        
      - name: test2
        shell: bash
        run: echo $PWD
      
      - name: test3
        shell: bash
        run: ls
      
      - name: test4
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release -B ./build-release
      
      - name: test5
        shell: bash
        run: cmake --build ./build-release

