name: build-and-test

on:
  push:
    branches: [ master ]

jobs:
  job:
    name: build-test.${{ matrix.config.os }}.${{ matrix.config.cxx }}.${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        build_type: ['Release']
        config:
        - {c: gcc-9, cxx: g++-9}
        #- {c: clang, cxx: clang++}
        
    steps:
      # Checks-out the repository and cd into it
      - uses: actions/checkout@v2
      
      - name: test0
        run: clang -v
      
      - name: test00
        run: clang++ -v
          
      - name: test1
        run: cmake -DCMAKE_C_COMPILER=${{ matrix.config.c }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
                   -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -B ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.config.c }}
          CXX: ${{ matrix.config.cxx }}
        
      - name: test2
        run: cmake --build ./build-${{ matrix.build_type }}
        env:
          CC:  ${{ matrix.config.c }}
          CXX: ${{ matrix.config.cxx }}
